config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foxes do
    post "adopt", on: :member
    get "unadopted", on: :collection

  end
  resources :users
  root to: "foxes#index"

end

app/models/fox.rb
class Fox < ActiveRecord::Base
  belongs_to :user

  def adopt user
    self.user = user
    self.save
  end

  def unadopted
    self.user = nil
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :foxes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foxes_controller.rb
class FoxesController < ApplicationController
  before_action :set_fox, only: [:show, :edit, :update, :destroy, :adopt]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # GET /foxes
  # GET /foxes.json
  def index
    @foxes = Fox.order("age")
  end

  def unadopted
    @foxes = Fox.where(user: nil)
    # hash = {imie: 'seb', nazwisko: 'esz'}
    #
    # hash[:imie] -> seb

  end

  # GET /foxes/1
  # GET /foxes/1.json
  def show
  end

  # GET /foxes/new
  def new
    @fox = Fox.new
  end

  # GET /foxes/1/edit
  def edit
  end

  # POST /foxes
  # POST /foxes.json
  def create
    @fox = Fox.new(fox_params)
    @fox.user = current_user

    respond_to do |format|
      if @fox.save
        format.html { redirect_to @fox, notice: 'Fox was successfully created.' }
        format.json { render :show, status: :created, location: @fox }
      else
        format.html { render :new }
        format.json { render json: @fox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foxes/1
  # PATCH/PUT /foxes/1.json
  def update
    respond_to do |format|
      if @fox.update(fox_params)
        format.html { redirect_to @fox, notice: 'Fox was successfully updated.' }
        format.json { render :show, status: :ok, location: @fox }
      else
        format.html { render :edit }
        format.json { render json: @fox.errors, status: :unprocessable_entity }
      end
    end
  end

  def adopt
    if @fox.user
      redirect_to foxes_path, notice: 'Ten lisek już ma właściciela'
    else
      @fox.adopt(current_user)
      redirect_to @fox, notice: 'Przygarnąłeś liska'
    end
  end

  # DELETE /foxes/1
  # DELETE /foxes/1.json
  def destroy
    @fox.unadopted
    respond_to do |format|
      format.html { redirect_to foxes_url, notice: 'Fox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fox
      @fox = Fox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fox_params
      params.require(:fox).permit(:name, :age, :color, :tail)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nick, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foxes_helper.rb
module FoxesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foxes/_form.html.erb
<%= form_for(@fox) do |f| %>
  <% if @fox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fox.errors.count, "error") %> prohibited this fox from being saved:</h2>

      <ul>
      <% @fox.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
<div class="field">
  <%= f.label :tail %><br>
  <%= f.text_field :tail %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foxes/edit.html.erb
<h1>Editing Fox</h1>

<%= render 'form' %>

<%= link_to 'Show', @fox %> |
<%= link_to 'Back', foxes_path %>

app/views/foxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Color</th>
      <th>Tail</th>
      <th>Ma właściciela?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foxes.each do |fox| %>
      <tr>
        <td><%= fox.name %></td>
        <td><%= fox.age %></td>
        <td><%= fox.color %></td>
        <td><%= fox.tail %></td>
        <td><% if fox.user %>
              <%= fox.user %>
              <% else %>
              <%= link_to "Adoptuj", adopt_fox_path(fox),method: :post %>
              <% end %></td>
        <td><%= link_to 'Show', fox %></td>
        <td><%= link_to 'Edit', edit_fox_path(fox) %></td>
        <td><%= link_to 'Osieroć', fox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fox', new_fox_path %>
|
<%= link_to 'Nie zaakceptowane', unadopted_foxes_path %>

app/views/foxes/new.html.erb
<h1>New Fox</h1>

<%= render 'form' %>

<%= link_to 'Back', foxes_path %>

app/views/foxes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @fox.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fox.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @fox.age %>
</p>

<p>
  <strong>Color:</strong>
  <%= @fox.color %>
</p>

<p>
  <strong>Tail:</strong>
  <%= @fox.tail %>
</p>
<p>
  <strong>Stworzony:</strong>
  <%= @fox.created_at %>
</p>


<%= link_to 'Edit', edit_fox_path(@fox) %> |
<%= link_to 'Back', foxes_path %>

app/views/foxes/unadopted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foxes</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Tail</th>
    <th>Ma właściciela?</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @foxes.each do |fox| %>
      <tr>
        <td><%= fox.name %></td>
        <td><%= fox.age %></td>
        <td><%= fox.color %></td>
        <td><%= fox.tail %></td>
        <td><% if fox.user %>
              <%= fox.user %>
          <% else %>
              <%= link_to "Adoptuj", adopt_fox_path(fox),method: :post %>
          <% end %></td>
        <td><%= link_to 'Show', fox %></td>
        <td><%= link_to 'Edit', edit_fox_path(fox) %></td>
        <td><%= link_to 'Osieroć', fox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fox', new_fox_path %> |
<%= link_to 'Wszystkie', foxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lesson4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
    <%= link_to "Wyloguj", destroy_user_session_path, method: :delete %> <br>
    Cześć, <%= current_user.email %>
<% else %>
    <%= link_to "Zaloguj się", new_user_session_path %>
    <%= link_to "Zarejestruj się", new_user_registration_path %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nick %><br>
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nick</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nick %></td>
        <td><%= user.city %></td>


        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nick:</strong>
  <%= @user.nick %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Liski:</strong>
  <% @user.foxes.each do |fox| %>
    <%= fox.name %>, 
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>